dags:
  - table: candy_factories
    owner: okza.pradhana
    start_date: 2024-10-18
    replace_if_exist: True
    catchup: False
    task_timeout: 5
    dag_timeout: 10
    schedule_interval: 0 1 * * *
  - table: candy_products
    owner: okza.pradhana
    start_date: 2024-10-18
    replace_if_exist: True
    catchup: False
    task_timeout: 5
    dag_timeout: 10
    schedule_interval: 0 1 * * *
  - table: candy_sales
    owner: okza.pradhana
    start_date: 2024-10-18
    replace_if_exist: True
    catchup: False
    task_timeout: 5
    dag_timeout: 10
    schedule_interval: 0 1 * * *
  - table: candy_targets
    owner: okza.pradhana
    start_date: 2024-10-18
    replace_if_exist: True
    catchup: False
    task_timeout: 5
    dag_timeout: 10
    schedule_interval: 0 1 * * *
